name: Docker

on:
  push:
    tags: ["v*.*.*"]
    branches: [ "main" ]

env:
  IMAGE_NAME: neume-user-service

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:latest
          file: service_users/Dockerfile
